version: '3.8'

services:
  agent:
    image: agent-app
    build:
      context: .
      target: agent
    environment:
      - ENV_VAR_NAME=value

  orchestrator:
    image: orchestrator-app
    build:
      context: .
      target: orchestrator
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR_NAME=value